import Login from "@/components/Login";
import { SessionProvider } from "@/components/SessionProvider";
import SideBar from "@/components/SideBar";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import "@/styles/globals.css";
import "@/styles/style.css";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="page-wrapper">
              <div className="sidebar-wrapper">
                <SideBar />
              </div>
              {/* Client Provider - Notification */}
              <div className="chat-wrapper">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
