import SideBar from '@/components/SideBar';
import '@/styles/globals.css'
import "@/styles/style.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="page-wrapper">
          <SideBar />
          {/* Client Provider - Notification */}
          <div className="chat-wrapper">{children}</div>
        </div>
      </body>
    </html>
  );
}
